#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file rrh-relation-changed
# brief called when a relation between an eNB and RRH is changed 
# author  navid.nikaein@eurecom.fr 

set -ex
source $CHARM_DIR/utils/common
set_env_paths

rrh_active=`relation-get RRH_ACTIVE`
hw=`relation-get TARGET_HARDWARE`
transport_mode=`relation-get TRANSPORT_MODE`
#locally selected hardware target
hw_config=`cat $CHARM_DIR/.hw`

if [ -z "$rrh_active" ]; then
   juju-log "Data not available yet, exit silently"
   exit 0
fi

if [ -z "$hw" ]; then
   juju-log "Data not available yet, exit silently"
   exit 0
fi

if [ -z "$transport_mode" ]; then
   juju-log "Data not available yet, exit silently"
   exit 0
fi

if [ "$transport_mode" == "raw" ]; then 
    tr_mode=1
else
    tr_mode=0
fi 


if [ "$rrh_active" == "yes" ]; then  

    echo "$rrh_active" >  $CHARM_DIR/.rrh_active
    # this will overwrite the rrh config
    echo "$tr_mode"  >  $CHARM_DIR/.tr_mode

    # this happens when the enb changes the target hardware
    if [ "$hw_config" != "$hw" ]; then

	echo "$hw" > $CHARM_DIR/.hw

	if [ "$hw" == "usrp" -o "$hw" == "USRP" ]; then
	    $build_path/build_oai -I -w USRP
	    $build_path/build_oai -C -c --RRH -t ETHERNET -w USRP
	elif [ "$hw" == "bladerf" -o "$hw" == "BLADERF" ]; then
	    $build_path/build_oai -I -w BLADERF
	    $build_path/build_oai -C -c --RRH -t ETHERNET -w BLADERF
	elif [ "$hw" == "sodera" -o "$hw" == "SODERA" -o "$hw" == "SoDeRa" ]; then
	    $build_path/build_oai -I -w LMSSDR
	    $build_path/build_oai -C -c --RRH -t ETHERNET -w LMSSDR
	elif [ "$hw" == "exmimo" -o "$hw" == "EXMIMO" ]; then
	    $build_path/build_oai -I 
	    $build_path/build_oai -C -c --RRH -t ETHERNET  -w EXMIMO
	else 
	    juju-log -l WARNING "Hardware option not valid, switching to EXMIMO"
	    echo "exmimo" > $CHARM_DIR/.hw
	    $build_path/build_oai -I 
	    $build_path/build_oai -C -c --RRH -t ETHERNET  -w EXMIMO
	fi
    fi 
    
    cp  $CHARM_DIR/.hw      $openair_path
    cp  $CHARM_DIR/.tr_mode $openair_path
    
    $CHARM_DIR/hooks/start
    #check the result
    status=$?
    if [ $status -eq 0 ]; then
	relation-set RRH_GW_RUNNING=yes
	status-set active "RRH GW is running"
    else 
	status-set blocked "RRH GW is not running"
    fi  
else 
    status-set blocked "RRH is not set to be active by eNB. Set the rrh_active"
fi
