#!/bin/bash
################################################################################
#
# Copyright (c) 2016, EURECOM (www.eurecom.fr)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are those
# of the authors and should not be interpreted as representing official policies,
# either expressed or implied, of the FreeBSD Project.
#
################################################################################
# file rrh-relation-joined
# brief called when a relation betwen an eNB and RRh is created 
# author  navid.nikaein@eurecom.fr 

set -eux
source $CHARM_DIR/utils/common
set_env_paths


juju-log "Setting up RRH GW relation for RRH charm"

relation-set RRH_GW_PORT=`config-get fronthaul_port`
relation-set RRH_GW_RUNNING=no

fh_if=`config-get fronthaul_if`
echo "$fh_if"  >  $CHARM_DIR/.fh_if
cp  $CHARM_DIR/.fh_if      $openair_path

#fh_ipv4=`ifconfig $fh_if | egrep -o "inet addr:[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" | egrep -o "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+"`
#relation-set RRH_GW_IP_ADDRESS=$fh_ipv4

rrh_public_ip=`unit-get public-address`
get_ip_address $rrh_public_ip
status=$?
if [ "$status" == "1" ] ; then
    status-set error "nslookup failed for the rrh host name ($rrh_public_ip)"
    relation-set RRH_GW_PUBLIC_IP=$rrh_public_ip
else
    relation-set RRH_GW_PUBLIC_IP=$validated_public_ip
    status-set maintenance "Joined the RRH relation"
fi 
